server:
  port: 8082

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
      
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**
        filters:
        - AddRequestHeader=X-SVC-KEY, dep-1234-5678
        - name: AuthorizationPreFilter
          args:
           groups: Admin, Roy2
      
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - AddRequestHeader=X-SVC-KEY, emp-1234-5678
        - name: AuthorizationPreFilter
          args:
           groups: Admin, Roy2

      - id: webfluxmongodb-service
        uri: lb://webfluxmongodb-service
        predicates:
        - Path=/webfluxmongodb/**
        filters:
        - AddRequestHeader=X-SVC-KEY, webfluxmongo-1234-5678
        - name: AuthorizationPreFilter
          args:
           groups: Admin, Roy2

      - id: department-swagger
        uri: lb://department-service
        predicates:
        - Path=/v3/api-docs/department/**
        filters:
        - AddRequestHeader=X-SVC-KEY, dep-1234-5678
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
                       
      - id: employee-swagger
        uri: lb://employee-service
        predicates:
        - Path=/v3/api-docs/employee/**
        filters:
        - AddRequestHeader=X-SVC-KEY, emp-1234-5678
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

      - id: webfluxmongodb-swagger
        uri: lb://webfluxmongodb-service
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - AddRequestHeader=X-SVC-KEY, webfluxmongo-1234-5678
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /    
auth:
  check-url: false
  check-auth: false
  token:
    header: authorization
    header-url: URL
    header-url-value: http://localhost
    user-info-header: user-info
   
app:
  eureka-username: u
  eureka-password: p        